### ISSUE TITLE
`Users` リソースを作成する

### ISSUE THREAD

**Issue by koyasaeki** [koyasaeki/stay-gold#1]
# `Users` リソースを作成する

## 概要

以下が行える `Users` リソースを作成する。

- 全ユーザーの取得
- 一意ユーザーの取得
- 新規ユーザーの登録
- 既存ユーザーの更新
- 既存ユーザーの削除

## エンドポイント

- `/users`
- `/users/:id`

## TODOs

- [x] 全ユーザー取得 API の作成
- [x] 一意ユーザー取得 API の作成
- [x] 新規ユーザー登録 API の作成
- [x] 既存ユーザー更新 API の作成
- [x] 既存ユーザー削除 API の作成
